import Head from "next/head";
import About from "../components/about";
import Layout from "../components/layout";

export default function AboutPage() {
  return (
    <div>
      <Head>
        <title>Website Test | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <About />
    </div>
  );
}
