import Head from "next/head";
import Layout from "../components/layout";

export default function ContactPage() {
  return (
    <div>
      <Head>
        <title>Website Test | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      </Layout>
    </div>
  );
}
