import Head from "next/head";
import Home from "../components/home";
import About from "../components/about";

export default function Homepage() {
  return (
    <div>
      <Head>
        <title>Website Test | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
      <About />
    </div>
  );
}
